config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get "users" => "user#index"
  get "users/new" => "user#new"
  post "users" => "user#create"
  delete "users/destroy/:id" => "user#destroy"
  get "users/edit/:id" => "user#edit"
  patch "users/update/:id" => "user#update"
  get "users/salary/:id" => "user#salaryedit"
  patch "users/salaryupdate/:id" => "user#salaryupdate"
  get "users/salarytotal/:id" => "user#salarytotal"
  get "users/:id" => "user#show"
  get '/' => "home#top"
  get 'admin/new' => "admin#new"
  post "admin/create" => "admin#create"
  get "admin/edit/:id" => "admin#edit"
  get "admin/index" => "admin#index"
  post "admin/update" => "admin#update"
  delete "admin/destroy/:id" => "admin#destroy"
  get "admin/public_holiday" => "admin#public_holiday"
  post "admin/set_holiday" => "admin#set_holiday"
  delete "admin/destroy_holiday/:id" => "admin#destroy_holiday"
  mount RailsAdmin::Engine => '/develop', as: 'rails_admin'
  get "admin/:id" => "admin#show"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
    <div class = "alert alert-warning" role = "alert">
        <ul>
            <% model.errors.full_messages.each do |message| %>

                <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>給料計算</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <p class="alert alert-primary" role="alert"><%= flash[:notice] %></p>
    <% end %>
    
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">給料計算</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if admin_signed_in? %>
        <li class="nav-item">
          <a class="nav-link" href="/admin/new">シフト表作成 <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/admin/index">シフト表一覧</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users">労働者管理</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/users/new">労働者新規作成</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="/admin/public_holiday">祝日設定</a>
        </li>

      <% else %>
        <li class="nav-item">
          <a class="nav-link disabled">シフト表作成 <span class="sr-only">(current)</span></a>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled">シフト表一覧</a>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled">労働者管理</a>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled">労働者新規作成</a>
        </li>

        <li class="nav-item">
          <a class="nav-link disabled">祝日設定</a>
        </li>
      
      <% end %>  
    </ul>
    <% if admin_signed_in? %>
        <div class = "nav-item">
          <span>管理者でログインしています </span>
          <%= link_to('ログアウト', destroy_admin_session_path, method: :delete) %>
        </div>
    <% else %>
      <div class = "nav-item">
        <%= link_to('管理者ログイン', new_admin_session_path,{class: "nav-link"}) %>
      </div>  
    <% end %>

    </div>
  </nav>
        
    </tr> 

    </table>
    <div class="container">
      <br />
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> 
  </body>
</html>